apiVersion: v1
kind: Service
metadata:
  name: invsvc-mysql
  labels:
    app: invsvc
spec:
  ports:
    - port: 3306
  selector:
    app: invsvc
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: invsvc
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invsvc-mysql
  labels:
    app: invsvc
spec:
  selector:
    matchLabels:
      app: invsvc
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: invsvc
        tier: mysql
    spec:
      containers:
      - image: rbodicherla/mysql-custom:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-password
              key: db-password
        - name: MYSQL_DATABASE
          value: qtinvsrv
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-password
              key: db-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
